AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Timeout: 30
        LoggingConfig:
            LogFormat: JSON

Resources:
    TablesStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: templates/tables.yaml

    BucketsStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: templates/buckets.yaml

    LambdasStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: templates/lambdas.yaml
