AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
    SocinizeApi:
        Type: AWS::Serverless::Api
        Properties:
            Name: SocinizeApi
            StageName: prod
            EndpointConfiguration: REGIONAL
            Cors:
                AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
                AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
                AllowOrigin: "'*'"

    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: HelloWorldFunction
            CodeUri: ../
            Handler: index.handler
            Runtime: nodejs20.x
            Architectures:
                - x86_64
            Description: 'A simple Hello World Lambda'
            MemorySize: 128
            Timeout: 10
            Events:
                ApiHelloWorld:
                    Type: Api
                    Properties:
                        RestApiId: !Ref SocinizeApi
                        Path: /hello
                        Method: GET
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Bundle: true
                Target: 'es2020'
                Sourcemap: true
                EntryPoints:
                    - src/hello-world/index.ts

Outputs:
    HelloWorldFunctionArn:
        Description: 'ARN of the HelloWorld Lambda'
        Value: !GetAtt HelloWorldFunction.Arn
        Export:
            Name: HelloWorldFunctionArn
    SocinizeApiId:
        Description: 'API Gateway ID'
        Value: !Ref SocinizeApi
        Export:
            Name: SocinizeApiId
    SocinizeApiEndpoint:
        Description: 'API Gateway endpoint URL'
        Value: !Sub 'https://${SocinizeApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
        Export:
            Name: SocinizeApiEndpoint
