AWSTemplateFormatVersion: '2010-09-09'
Resources:
    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: HelloWorldFunction
            CodeUri: .
            Handler: index.handler
            Runtime: nodejs20.x
            Architectures:
                - x86_64
            Description: 'A simple Hello World Lambda'
            MemorySize: 128
            Timeout: 10
            Events:
                ApiHelloWorld:
                    Type: Api
                    Properties:
                        RestApiId:
                            Fn::ImportValue: SocinizeApiId
                        Path: /hello
                        Method: GET
            Metadata:
                BuildMethod: esbuild
                BuildProperties:
                    Minify: true
                    Bundle: true
                    Target: 'es2020'
                    Sourcemap: true
                    EntryPoints:
                        - src/hello-world/index.ts

Outputs:
    HelloWorldFunctionArn:
        Description: 'ARN of the HelloWorld Lambda'
        Value: !GetAtt HelloWorldFunction.Arn
        Export:
            Name: HelloWorldFunctionArn
