AWSTemplateFormatVersion: '2010-09-09'
Resources:
    UsersTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Users
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: user_id
                  AttributeType: S
            KeySchema:
                - AttributeName: user_id
                  KeyType: HASH

    PostsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: Posts
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: post_id
                  AttributeType: S
                - AttributeName: user_id
                  AttributeType: S
            KeySchema:
                - AttributeName: post_id
                  KeyType: HASH
            GlobalSecondaryIndexes:
                - IndexName: UserPostsIndex
                  KeySchema:
                      - AttributeName: user_id
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL

    SocialAccountsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: SocialAccounts
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: account_id
                  AttributeType: S
                - AttributeName: user_id
                  AttributeType: S
            KeySchema:
                - AttributeName: account_id
                  KeyType: HASH
            GlobalSecondaryIndexes:
                - IndexName: UserAccountsIndex
                  KeySchema:
                      - AttributeName: user_id
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL

Outputs:
    UsersTableName:
        Description: 'Users DynamoDB Table Name'
        Value: !Ref UsersTable
        Export:
            Name: UsersTableName
    PostsTableName:
        Description: 'Posts DynamoDB Table Name'
        Value: !Ref PostsTable
        Export:
            Name: PostsTableName
    SocialAccountsTableName:
        Description: 'SocialAccounts DynamoDB Table Name'
        Value: !Ref SocialAccountsTable
        Export:
            Name: SocialAccountsTableName
